#setwd("C:/Users/rusla/OneDrive/MLBAnalyticsJobs/MLB Swing Decision & Pitch Quality Leaderboards/R Shiny")
source("./functions.R")
source("./set_up_shiny.R")
full_preds21 <- fread("./pitch_by_pitch21.csv", encoding = 'UTF-8')
full_preds22 <- fread("./pitch_by_pitch22.csv", encoding = 'UTF-8')
full_preds23 <- fread("./pitch_by_pitch23.csv", encoding = 'UTF-8')
full_preds22$pitcher_team <- ifelse(full_preds22$pitcher_team == "Indians", "Guardians", full_preds22$pitcher_team)
full_preds22$batter_team <- ifelse(full_preds22$batter_team == "Indians", "Guardians", full_preds22$batter_team)
full_preds23$pitcher_team <- ifelse(full_preds23$pitcher_team == "Indians", "Guardians", full_preds23$pitcher_team)
full_preds23$batter_team <- ifelse(full_preds23$batter_team == "Indians", "Guardians", full_preds23$batter_team)
shiny <- set_up_shiny(full_preds21, full_preds22, full_preds23)
shinyApp(ui = shiny[[1]], server = shiny[[2]])
