library('baseballr')
library('ggplot2')
library('dplyr')
library('stringr')
library('kableExtra')
library("CalledStrike")
library('shiny')
library('GeomMLBStadiums')
library('patchwork')
library('readr')
library('gridExtra')
library('ggpointdensity')
require('mgcv')
`%!in%` = Negate(`%in%`)

setwd("C:/Users/rusla/OneDrive/MLBAnalyticsJobs/Trackman_Shiny_App")
source("functions.R")

fg_hitter <- fg_bat_leaders(x = 2021, y = 2021, league = "all", qual = 50, ind = 1)
hitters_list <- fg_hitter %>% tidyr::separate(col = Name, into = c("First", "Last"), sep = "\\s") %>% select(First, Last) %>% distinct()
hitters_list$name <- as.character(interaction(hitters_list,sep=" "))

fg_pitchers <- fg_pitch_leaders(x = 2021, y = 2021, league = "all", qual = 20, ind = 1)
pitchers_list <- fg_pitchers %>% tidyr::separate(col = Name, into = c("First", "Last"), sep = "\\s") %>% select(First, Last) %>% distinct()
pitchers_list$name <- as.character(interaction(pitchers_list,sep=" "))

source("set_up_shiny.R")
shiny <- set_up_shiny()
shinyApp(ui = shiny[[1]], server = shiny[[2]])
