#setwd("C:/Users/rusla/OneDrive/MLBAnalyticsJobs/MLB Statcast Leaderboards")
library(dplyr)
library(baseballr)
library(shiny)
library(kableExtra)
library(reactable)
library(DT)
library(stringr)
source("./functions.R")
source("./set_up_shiny.R")
shiny <- set_up_shiny()
shinyApp(ui = shiny[[1]], server = shiny[[2]])
